name: my-app
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set Up JDK 17
        uses: actions/setup-java@v1
        with: 
          java-version: 17

      - name: Set Up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest

      - name: Check Chrome Version
        run: google-chrome --version

      - name: Install Chrome Dependencies
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - name: Verify Maven Dependencies
        run: mvn dependency:tree

      - name: Run Tests with Maven and TestNG
        run: mvn -B clean test
        env:
          MAVEN_OPTS: "-Xmx2g"  # Set memory limits to avoid resource issues

      - name: Check TestNG Results
        run: cat target/surefire-reports/testng-results.xml

      - name: Upload Test Reports (in case of failures)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/
